services:
  db:
    container_name: postgres_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - db_network

  db_explorer: 
    container_name: pgadmin_explorer
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_vol:
  pgadmin_vol: